Make stubbed calls more thread safe
Brightify/Cuckoo pull request #392
Opened 2021-05-11 13:08 UTC by ChaosCoder

This PR adds thread safety around memorizing stub calls inside the MockManager.

Calling stubbed methods from a multithreading environment lead to crashing. By using a private queue for synchronizing write access to the appropriate collections calling stubs multithreaded is no longer a problem.

Resolves #298 and supersedes #351.

2021-05-13 06:51 UTC, MatyasKriz requested changes

2021-05-13 06:51 UTC, MatyasKriz commented on Source/MockManager.swift
> +            queue.sync {
With this configuration I think it's better to change the variable into a constant like so:
```
let action = queue.sync {
  if !stub.actions.isEmpty {
    return stub.actions.removeFirst()
  } else {
    return nil
  }
}
```

2021-05-13 06:51 UTC, MatyasKriz commented on Source/MockManager.swift
> +                    queue.sync { _ = stub.actions.removeFirst() }
Why does it need to be inside another `queue.sync` here?

2021-05-13 06:52 UTC, MatyasKriz commented
Thanks for the PR, @ChaosCoder! It looks good, although it can be a bit better. 🙂

2021-05-13 18:30 UTC, ChaosCoder commented on Source/MockManager.swift
> +            queue.sync {
Your suggestion actually changes the logic (in the case of `stub.actions.count == 1`, but I agree, the constant is nicer. I pushed another commit.

2021-05-13 18:30 UTC, ChaosCoder commented on Source/MockManager.swift
> +                    queue.sync { _ = stub.actions.removeFirst() }
Good catch, that was an error.

2021-05-13 20:14 UTC, MatyasKriz commented on Source/MockManager.swift
> +            queue.sync {
Yeah, my bad, sorry. Didn't read the code properly.

2021-05-13 20:16 UTC, MatyasKriz commented
Thanks for resolving the issues so quickly! Looks great and I will try to merge this as soon as I can. 🙂

2021-05-17 08:17 UTC, MatyasKriz approved these changes

2021-05-25 15:09 UTC, MatyasKriz commented
Thanks again for the PR! I've merged it and will release it shortly.

2021-05-27 16:02 UTC, ChaosCoder commented
So, just to make sure this does not get lost: this PR is still not merged. ;)

2021-05-27 16:04 UTC, closed without merging