Fix compiling generated code for platform where given APIs are marked unavailable
Brightify/Cuckoo pull request #423
Opened 2022-04-27 12:43 UTC by rolandkakonyi

# Problem
In case of a cross-platform codebase where some APIs are marked with e.g. `@available(tvOS, unavailable)` the Cuckoo generated code can not be compiled due to error `Cannot override 'tvOSUnavailableAPI' which has been marked unavailable` when building for the "forbidden" platform.

Like with this type to mock:

```swift
class TestClass {
    @available(tvOS, unavailable)
    var tvOSUnavailableAPI: Bool = true
} 
```

I am happy to take any feedback.
I didn't know how to add unit tests for this project (seems a bit unconventional 😅 ), but happy to do so if I get some instructions how the setup works. 

# Proposed solution
I have built a POC where I extracted the platform value (`"tvOS"` from the above example) and wrapped the affected API with `#if !os(unavailablePlatform)`.

In case of multiple unavailable platforms:
```swift
class TestClass {
    @available(tvOS, unavailable)
    @available(macCatalyst, unavailable)
    var tvOSUnavailableAPI: Bool = true

    var generallyAvailableApi: String = "hello"
}
```

it would result like this: `#if !os(tvOS) && !os(macCatalyst)` (see below)

## Generated code
```swift
// MARK: - Mocks generated from file: SourceFiles/ClassWithAttributes.swift

import Cuckoo

 class MockTestClass: TestClass, Cuckoo.ClassMock {
    
     typealias MocksType = TestClass
    
     typealias Stubbing = __StubbingProxy_TestClass
     typealias Verification = __VerificationProxy_TestClass

     let cuckoo_manager = Cuckoo.MockManager.preconfiguredManager ?? Cuckoo.MockManager(hasParent: true)

    
    private var __defaultImplStub: TestClass?

     func enableDefaultImplementation(_ stub: TestClass) {
        __defaultImplStub = stub
        cuckoo_manager.enableDefaultStubImplementation()
    }
    

    
    
    #if !os(macCatalyst) && !os(tvOS)
    
    
    
    @available(macCatalyst, unavailable)
    
    @available(tvOS, unavailable)
    
     override var tvOSUnavailableAPI: Bool {
        get {
            return cuckoo_manager.getter("tvOSUnavailableAPI",
                superclassCall:
                    
                    super.tvOSUnavailableAPI
                    ,
                defaultCall: __defaultImplStub!.tvOSUnavailableAPI)
        }
        
        set {
            cuckoo_manager.setter("tvOSUnavailableAPI",
                value: newValue,
                superclassCall:
                    
                    super.tvOSUnavailableAPI = newValue
                    ,
                defaultCall: __defaultImplStub!.tvOSUnavailableAPI = newValue)
        }
        
    }
    
    #endif
    
    
    
    
    
     override var generallyAvailableApi: String {
        get {
            return cuckoo_manager.getter("generallyAvailableApi",
                superclassCall:
                    
                    super.generallyAvailableApi
                    ,
                defaultCall: __defaultImplStub!.generallyAvailableApi)
        }
        
        set {
            cuckoo_manager.setter("generallyAvailableApi",
                value: newValue,
                superclassCall:
                    
                    super.generallyAvailableApi = newValue
                    ,
                defaultCall: __defaultImplStub!.generallyAvailableApi = newValue)
        }
        
    }
    
    

    

    

	 struct __StubbingProxy_TestClass: Cuckoo.StubbingProxy {
	    private let cuckoo_manager: Cuckoo.MockManager
	
	     init(manager: Cuckoo.MockManager) {
	        self.cuckoo_manager = manager
	    }
	    
	    
	    #if !os(macCatalyst) && !os(tvOS)
	    
	    
	    @available(macCatalyst, unavailable)
	    
	    @available(tvOS, unavailable)
	    
	    var tvOSUnavailableAPI: Cuckoo.ClassToBeStubbedProperty<MockTestClass, Bool> {
	        return .init(manager: cuckoo_manager, name: "tvOSUnavailableAPI")
	    }
	    
	    #endif
	    
	    
	    
	    
	    var generallyAvailableApi: Cuckoo.ClassToBeStubbedProperty<MockTestClass, String> {
	        return .init(manager: cuckoo_manager, name: "generallyAvailableApi")
	    }
	    
	    
	    
	}

	 struct __VerificationProxy_TestClass: Cuckoo.VerificationProxy {
	    private let cuckoo_manager: Cuckoo.MockManager
	    private let callMatcher: Cuckoo.CallMatcher
	    private let sourceLocation: Cuckoo.SourceLocation
	
	     init(manager: Cuckoo.MockManager, callMatcher: Cuckoo.CallMatcher, sourceLocation: Cuckoo.SourceLocation) {
	        self.cuckoo_manager = manager
	        self.callMatcher = callMatcher
	        self.sourceLocation = sourceLocation
	    }
	
	    
	    
	    #if !os(macCatalyst) && !os(tvOS)
	    
	    
	    @available(macCatalyst, unavailable)
	    
	    @available(tvOS, unavailable)
	    
	    var tvOSUnavailableAPI: Cuckoo.VerifyProperty<Bool> {
	        return .init(manager: cuckoo_manager, name: "tvOSUnavailableAPI", callMatcher: callMatcher, sourceLocation: sourceLocation)
	    }
	    
	    #endif
	    
	    
	    
	    
	    var generallyAvailableApi: Cuckoo.VerifyProperty<String> {
	        return .init(manager: cuckoo_manager, name: "generallyAvailableApi", callMatcher: callMatcher, sourceLocation: sourceLocation)
	    }
	    
	    
	
	    
	}
}

 class TestClassStub: TestClass {
        
    
    #if !os(macCatalyst) && !os(tvOS)
    
    
    
    @available(macCatalyst, unavailable)
    
    @available(tvOS, unavailable)
    
     override var tvOSUnavailableAPI: Bool {
        get {
            return DefaultValueRegistry.defaultValue(for: (Bool).self)
        }
        
        set { }
        
    }
    
    #endif
    
        
    
    
    
     override var generallyAvailableApi: String {
        get {
            return DefaultValueRegistry.defaultValue(for: (String).self)
        }
        
        set { }
        
    }
    
    

    

    
}

```

2022-04-29 08:21 UTC, rolandkakonyi commented
friendly ping to @MatyasKriz for visibility :)

2022-05-02 19:59 UTC, MatyasKriz requested changes

2022-05-02 19:59 UTC, MatyasKriz commented on Generator/Source/CuckooGeneratorFramework/Templates/MockTemplate.swift
> +#if !os({{ container.unavailablePlatforms|join:") && !os(" }})
What do you think about moving this into Swift instead? It's in quite a few places here.

2022-05-02 19:59 UTC, MatyasKriz commented on Generator/Source/CuckooGeneratorFramework/Tokens/Attribute.swift
> +              text.hasPrefix("@available(") else {
Why is the additional prefix check needed? Just a sanity check?

2022-05-02 19:59 UTC, MatyasKriz commented on Generator/Source/CuckooGeneratorFramework/Tokens/Attribute.swift
> +                .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
Please drop the indentation by one level.

2022-05-02 19:59 UTC, MatyasKriz commented on Generator/Source/CuckooGeneratorFramework/Tokens/Attribute.swift
> +        guard let unavailablePlatform = parameters.first else {
Since the `guard` above sanity checks the count, I think you can just use subscript with index 0. 🙂 I'm not against the safety, but rather prefer the conciseness here.

2022-05-02 19:59 UTC, MatyasKriz commented on Generator/Source/CuckooGeneratorFramework/Tokens/Attribute.swift
> +                .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
Also, I like the functional approach. 🙂

2022-05-02 20:03 UTC, MatyasKriz commented
Sorry, misclick. 😅 Overall the PR seems solid. 🙂 The way we test the generator itself is not against a hardcoded file, but instead just by adding the functionality, running the tests which regenerates the file, and checking if the Swift compiler is fine with it.

2022-05-03 07:44 UTC, rolandkakonyi commented on Generator/Source/CuckooGeneratorFramework/Tokens/Attribute.swift
> +              text.hasPrefix("@available(") else {
it was only sanity check, as we get the type of attribute from SourceKit and we have to parse the platform manually. Therefore no guarantee of its grammar, so it felt right to do a sanity check.

2022-05-03 07:53 UTC, rolandkakonyi commented on Generator/Source/CuckooGeneratorFramework/Tokens/Attribute.swift
> +                .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
fixed in a894323

2022-05-03 07:54 UTC, rolandkakonyi commented on Generator/Source/CuckooGeneratorFramework/Tokens/Attribute.swift
> +        guard let unavailablePlatform = parameters.first else {
makes sense, fixed in 476568b

2022-05-03 08:16 UTC, rolandkakonyi commented on Generator/Source/CuckooGeneratorFramework/Templates/MockTemplate.swift
> +#if !os({{ container.unavailablePlatforms|join:") && !os(" }})
Did you mean to join `unavailablePlatforms` in Swift before passing to the templating engine?

My thought process was that forming the `#if !os(x) && !os(y)` checks belongs to the template as `unavailablePlatforms` is only the data to drive it, while the template can decide how to utilize it.
Until now I considered generated code grammar being a template concern, BUT as I just checked now that generic parameters are already built in Swift.

No strong opinion, I will refactor this to Swift, I was annoyed of repeating this anyway :)

2022-05-03 08:51 UTC, rolandkakonyi commented on Generator/Source/CuckooGeneratorFramework/Templates/MockTemplate.swift
> +#if !os({{ container.unavailablePlatforms|join:") && !os(" }})
I moved the String construction to Swift in commit: da449b3aaecbbdf5095d893ec7c7a45346e6b369

I took the extra mile in 5b11f49b032fe9bdb939fa17438294ef3e74919a to reduce code duplication. Feedback is welcome!

2022-05-30 07:00 UTC, rolandkakonyi commented
@MatyasKriz any additional feedback on this?

2022-05-30 17:04 UTC, MatyasKriz commented
> @MatyasKriz any additional feedback on this?

Sorry, is there a forgotten commit containing the tests? Just using the `@available(tvOS, unavailable)` and verifying that the implementation works correctly and the generated code is compilable is enough. 🙂

2022-06-06 10:46 UTC, rolandkakonyi commented
@MatyasKriz You can find the tests in this commit: 791c0a7

Feedback is welcome!

2022-06-07 19:40 UTC, MatyasKriz commented
> @MatyasKriz You can find the tests in this commit: [7b197ce](https://github.com/Brightify/Cuckoo/commit/7b197cebdb23ef5ffa9dbd8487881e2c639aae76)
> 
> Feedback is welcome!

The tests seem quite extensive, though when added to the xcodeproj and running tests, they aren't compilable and the resultant generated mocks aren't neither. If the generated code doesn't reflect the newest changes to the generator, you may need to run `./run --clean` to build a new generator using the current source code.

Please try running all the schemes `Cuckoo-iOS`, `Cuckoo-macOS`, and `Cuckoo-tvOS` to see if they're compilable. 🙂

2022-06-08 06:38 UTC, rolandkakonyi commented
@MatyasKriz thank you for the detailed steps, all fixed now in commit: c485a1332214dba88596192c7860132b9afadb84
All tests are passing now!

What I missed there was to add the test files to `Cuckoo.xcodeproj`, somehow I assumed since it is a package new files are picked up automatically.

2022-06-17 15:47 UTC, MatyasKriz commented
> @MatyasKriz thank you for the detailed steps, all fixed now in commit: [c485a13](https://github.com/Brightify/Cuckoo/commit/c485a1332214dba88596192c7860132b9afadb84) All tests are passing now!
> 
> What I missed there was to add the test files to `Cuckoo.xcodeproj`, somehow I assumed since it is a package new files are picked up automatically.

Yeah, sorry about that, I've been meaning to switch to Tuist fully, which would allow to just add the files and have the project pick it up automatically.

Anyway, the pull request looks good to me, thanks a lot for implementing the feature! 🙂

2022-06-17 15:50 UTC, closed without merging